from app.constants.source_categories import SOURCE_CATEGORIES

KEYWORD_MAP = {
    "altex": [
        (["telefon", "iphone", "samsung galaxy", "smartphone",
          "xiaomi", "huawei", "oppo", "realme"],
         "Telefoane, Tablete, Accesorii", "Telefoane mobile"),
        (["tableta", "ipad", "tab "],
         "Telefoane, Tablete, Accesorii", "Tablete"),
        (["smartwatch", "galaxy watch", "apple watch"],
         "Telefoane, Tablete, Accesorii", "Smartwatch-uri"),
        (["laptop", "notebook", "macbook", "chromebook"],
         "Laptop, Desktop, IT, Birotica", "Laptopuri"),
        (["monitor "],
         "Laptop, Desktop, IT, Birotica", "Monitoare"),
        (["televizor", "tv ", "oled", "qled"],
         "Televizoare, Audio-Video, Foto-Video", "Televizoare"),
        (["casti ", "earbuds", "airpods"],
         "Televizoare, Audio-Video, Foto-Video", "Casti audio"),
        (["aparat foto", "mirrorless", "dslr"],
         "Televizoare, Audio-Video, Foto-Video", "Aparate foto mirrorless"),
        (["frigider", "combine frigorific"],
         "Electrocasnice mari", "Frigidere"),
        (["masina de spalat", "masina spalat"],
         "Electrocasnice mari", "Masini de spalat rufe"),
        (["aspirator robot"],
         "Electrocasnice mici, Vesela", "Aspiratoare robot"),
        (["aspirator"],
         "Electrocasnice mici, Vesela", "Aspiratoare"),
        (["espressor", "cafetiera", "capsule"],
         "Electrocasnice mici, Vesela", "Espressoare"),
        (["aer conditionat", "aer condit"],
         "Racire, Purificare aer, Incalzire", "Aere conditionate"),
        (["consola", "playstation", "xbox", "nintendo"],
         "Gaming, Jocuri, Carti", "Console gaming"),
    ],
    "emag": [
        (["telefon", "iphone", "smartphone", "samsung galaxy"],
         "Laptop, Tablete & Telefoane", "Telefoane Mobile"),
        (["laptop", "notebook", "macbook"],
         "Laptop, Tablete & Telefoane", "Laptop / Notebook"),
        (["tableta", "ipad"],
         "Laptop, Tablete & Telefoane", "Tablete"),
        (["smartwatch", "galaxy watch", "apple watch"],
         "Laptop, Tablete & Telefoane", "Smartwatch-uri"),
        (["placa video", "gpu", "rtx", "rx "],
         "PC, Periferice & Software", "Placi video"),
        (["ssd ", "nvme"],
         "PC, Periferice & Software", "SSD"),
        (["televizor", "tv ", "oled", "qled"],
         "TV, Audio-Video & Foto", "Televizoare"),
        (["aparat foto", "mirrorless", "dslr"],
         "TV, Audio-Video & Foto", "Aparate foto mirrorless"),
        (["casti ", "earbuds", "airpods", "headphones"],
         "TV, Audio-Video & Foto", "Casti wireless"),
        (["frigider", "combine frigorific"],
         "Electrocasnice & Climatizare", "Frigidere"),
        (["masina de spalat"],
         "Electrocasnice & Climatizare", "Masini de spalat rufe"),
        (["aspirator robot"],
         "Electrocasnice & Climatizare", "Aspiratoare robot"),
        (["aer conditionat"],
         "Electrocasnice & Climatizare", "Aere conditionate"),
        (["consola", "playstation", "xbox", "nintendo"],
         "Gaming, Carti & Birotica", "Console gaming"),
    ],
    "pcgarage": [
        (["laptop", "notebook", "macbook"],
         "Laptop & Notebook", "Laptop gaming"),
        (["placa video", "gpu", "rtx", "gtx", "rx "],
         "Componente PC", "Placi video"),
        (["procesor", "cpu", "ryzen", "core i"],
         "Componente PC", "Procesoare"),
        (["ssd ", "nvme", "m.2"],
         "Componente PC", "SSD"),
        (["memorie ram", "ddr"],
         "Componente PC", "Memorii RAM"),
        (["monitor "],
         "Periferice", "Monitoare"),
        (["tastatura"],
         "Periferice", "Tastaturi"),
        (["mouse "],
         "Periferice", "Mouse-uri"),
        (["casti gaming"],
         "Periferice", "Casti gaming"),
        (["router", "wi-fi", "wifi"],
         "Retea & Conectivitate", "Routere wireless"),
        (["ups "],
         "Retea & Conectivitate", "UPS"),
        (["televizor", "tv "],
         "TV & Audio", "Televizoare"),
        (["imprimanta", "multifunctionala"],
         "Printing", "Imprimante"),
    ],
    "farmaciatei": [
        (["vitamina", "vitamina c", "vitamina d", "zinc", "magneziu",
          "omega", "probiotic"],
         "Vitamine & Suplimente", "Vitamine si minerale"),
        (["crema ten", "ser ten", "masca ten"],
         "Dermato-cosmetice", "Creme si seruri ten"),
        (["protectie solara", "spf", "sunscreen"],
         "Dermato-cosmetice", "Protectie solara"),
        (["parfum"],
         "Cosmetice premium", "Parfumuri"),
        (["tensiometru"],
         "Dispozitive medicale", "Tensiometre"),
        (["termometru"],
         "Dispozitive medicale", "Termometre"),
        (["hrana caine", "hrana pisica", "hrana animale"],
         "Animale de companie", "Hrana caini"),
    ],
    "sole": [
        (["spf", "protectie solara", "sunscreen", "autobronzant"],
         "Protectie solara", "Creme protectie solara fata"),
        (["ser ", "serum", "ampoule"],
         "Ingrijire ten", "Seruri pentru ten"),
        (["crema de zi", "crema hidratanta"],
         "Ingrijire ten", "Creme de zi"),
        (["masca ten", "sheet mask"],
         "Ingrijire ten", "Masti pentru ten"),
        (["sampon", "balsam par", "masca par"],
         "Ingrijire par", "Sampoane"),
        (["gel de dus", "crema de corp", "lotiune corp"],
         "Ingrijire corp", "Geluri de dus"),
        (["fond de ten", "concealer", "rimel", "ruj"],
         "Machiaj", "Fond de ten"),
        (["parfum"],
         "Parfumuri", "Parfumuri femei"),
    ],
}


def infer_category_from_name(
    product_name: str,
    source: str
) -> tuple[str | None, str | None]:
    """
    Incearca sa infereze categoria principala si subcategoria
    pe baza numelui produsului si a sursei.
    Returneaza (main_category, subcategory) sau (None, None).
    """
    name_lower = (product_name or "").lower()
    for keywords, main_cat, sub_cat in KEYWORD_MAP.get(source, []):
        if any(kw in name_lower for kw in keywords):
            return main_cat, sub_cat
    return None, None
