SOURCE_CATEGORIES = {
    "altex": {
        "Telefoane, Tablete, Accesorii": [
            "Telefoane mobile", "Tablete", "Smartwatch-uri",
            "Bratari fitness", "Casti Bluetooth",
            "Huse si folii telefoane", "Accesorii telefoane",
            "Accesorii tablete", "Incarcatoare si baterii externe",
        ],
        "Laptop, Desktop, IT, Birotica": [
            "Laptopuri", "Calculatoare desktop", "All-in-One PC",
            "Mini PC", "Monitoare", "Tastaturi", "Mouse-uri",
            "Imprimante", "Multifunctionale", "Scanere",
            "Routere wireless", "Switch-uri", "NAS", "UPS",
            "Cabluri si adaptoare", "Accesorii laptop", "Software",
        ],
        "Gaming, Jocuri, Carti": [
            "Console gaming", "Jocuri PC", "Jocuri console",
            "Casti gaming", "Scaune gaming", "Birouri gaming",
            "Mouse gaming", "Tastaturi gaming",
            "Controllere si gamepad-uri", "Carti",
        ],
        "Televizoare, Audio-Video, Foto-Video": [
            "Televizoare", "Soundbar-uri si home cinema",
            "Amplificatoare", "Boxe portabile", "Casti audio",
            "Aparate foto DSLR", "Aparate foto compacte",
            "Aparate foto mirrorless", "Camere video",
            "Drone", "Proiectoare", "Accesorii foto-video",
        ],
        "Electrocasnice mari": [
            "Frigidere", "Combine frigorifice", "Congelatoare",
            "Masini de spalat rufe", "Uscatoare de rufe",
            "Masini de spalat cu uscare", "Aragaze si cuptoare",
            "Cuptoare incorporate", "Hote de bucatarie",
            "Masini de spalat vase", "Plite incorporabile",
        ],
        "Electrocasnice mici, Vesela": [
            "Aspiratoare", "Aspiratoare robot", "Cafetiere",
            "Espressoare", "Blendere si mixere", "Multicooker",
            "Friteuze cu aer", "Fiare de calcat", "Statii de calcat",
            "Epilatoare", "Aparate de coafat", "Aparate de ras",
            "Perii de dinti electrice", "Vase si accesorii bucatarie",
        ],
        "Racire, Purificare aer, Incalzire": [
            "Aere conditionate", "Ventilatoare",
            "Purificatoare de aer", "Dezumidificatoare",
            "Umidificatoare", "Radiatoare electrice",
            "Calorifere", "Convectoare", "Termostate",
        ],
        "Curatenie, Intretinere casa": [
            "Aspiratoare verticale", "Mopuri electrice",
            "Generatoare de aburi", "Accesorii curatenie",
        ],
        "Bauturi, Cafea, Petshop": [
            "Capsule cafea", "Cafea boabe", "Cafea macinata",
            "Accesorii barista", "Hrana caini",
            "Hrana pisici", "Accesorii animale de companie",
        ],
        "Cosmetice, Beauty, Sanatate": [
            "Parfumuri barbati", "Parfumuri femei",
            "Creme si lotiuni", "Ingrijire par",
            "Ingrijire corp", "Ingrijire ten",
            "Aparate de masaj", "Tensiometre", "Termometre",
        ],
        "Copii, Jucarii, Bebe": [
            "Jucarii copii", "LEGO", "Jocuri educative",
            "Carucioare", "Scaune auto copii",
            "Baby monitor", "Articole bebelusi",
        ],
        "Bricolaj, Sanitare, Mobila": [
            "Scule electrice", "Scule manuale",
            "Becuri si iluminat", "Prize si intrerupatoare",
            "Sisteme alarma", "Camere supraveghere", "Smart home",
        ],
        "Anvelope, Electronica auto": [
            "Anvelope vara", "Anvelope iarna",
            "Anvelope all season", "GPS auto",
            "Camera video auto", "Alarme auto", "Accesorii auto",
        ],
        "Trotinete, Biciclete, Sport, Voiaj": [
            "Trotinete electrice", "Biciclete electrice",
            "Biciclete", "Echipament fitness",
            "Articole sport", "Bagaje si troler", "Rucsacuri",
        ],
    },

    "emag": {
        "Laptop, Tablete & Telefoane": [
            "Laptop / Notebook", "Laptopuri Gaming",
            "Laptopuri Business", "Laptopuri 2 in 1",
            "Laptopuri Home", "Genti laptop", "Docking stations",
            "Standuri si coolere notebook", "Incarcatoare laptop",
            "Baterii laptop", "Memorii notebook",
            "Hard disk-uri notebook", "Accesorii laptop",
            "Folii protectie laptop", "Telefoane Mobile",
            "Huse telefoane", "Folii protectie telefoane",
            "Incarcatoare telefoane", "Baterii telefoane",
            "Power bank", "Casti audio telefoane",
            "Smartwatch-uri", "Bratari fitness",
            "Accesorii smartwatch", "Tablete",
            "Huse tablete", "Accesorii tablete", "eBook readere",
        ],
        "PC, Periferice & Software": [
            "Desktop PC", "All-in-One PC", "Mini PC",
            "Monitoare", "Placi video", "Procesoare",
            "Placi de baza", "Memorii RAM", "SSD", "HDD",
            "Surse PC", "Carcase", "Coolere procesor",
            "Ventilatoare carcasa", "Pasta termoconductoare",
            "Tastaturi", "Mouse-uri", "Mousepad-uri",
            "Casti audio PC", "Webcam-uri", "Microfoane",
            "Imprimante", "Multifunctionale", "Scanere",
            "Cartuse si tonere", "Imprimante 3D",
            "Routere", "Switch-uri", "Access point",
            "NAS", "Cabluri retea", "UPS",
            "Servere", "Rack-uri server",
            "Camere supraveghere", "Sisteme alarma",
            "Software sisteme de operare", "Software office",
            "Antivirus", "Cabluri si adaptoare",
            "Carduri de memorie", "USB flash drive",
            "SSD extern", "HDD extern",
        ],
        "TV, Audio-Video & Foto": [
            "Televizoare", "Televizoare OLED", "Televizoare QLED",
            "Televizoare 4K", "Televizoare 8K", "Televizoare Smart",
            "Accesorii TV", "Suporturi TV", "Proiectoare",
            "Ecrane proiectie", "Sisteme home cinema",
            "Soundbar-uri", "Amplificatoare audio", "Receivere AV",
            "Boxe portabile", "Boxe de raft", "Casti audio",
            "Casti wireless", "Aparate foto DSLR",
            "Aparate foto mirrorless", "Aparate foto compacte",
            "Obiective foto", "Accesorii foto", "Trepieduri",
            "Camere video", "Camere actiune",
            "Drone", "Accesorii drone",
        ],
        "Electrocasnice & Climatizare": [
            "Frigidere", "Combine frigorifice", "Congelatoare",
            "Lazi frigorifice", "Vitrine frigorifice",
            "Masini de spalat rufe", "Uscatoare de rufe",
            "Masini de spalat cu uscare", "Aragaze", "Plite",
            "Cuptoare incorporate", "Cuptoare cu microunde",
            "Hote", "Masini de spalat vase",
            "Aere conditionate", "Ventilatoare",
            "Purificatoare de aer", "Dezumidificatoare",
            "Umidificatoare", "Radiatoare electrice", "Termostate",
            "Aspiratoare", "Aspiratoare robot",
            "Aspiratoare verticale", "Spalatoare cu presiune",
            "Cafetiere", "Espressoare", "Capsule cafea",
            "Blendere", "Mixere", "Multicooker",
            "Friteuze cu aer", "Grill-uri electrice",
            "Masini de facut paine", "Fiare de calcat",
            "Statii de calcat",
        ],
        "Gaming, Carti & Birotica": [
            "Console gaming", "PlayStation 5", "Xbox Series X/S",
            "Nintendo Switch", "Jocuri PlayStation", "Jocuri Xbox",
            "Jocuri Nintendo", "Jocuri PC",
            "Controllere si gamepad-uri", "Volan gaming",
            "Casti gaming", "Scaune gaming", "Birouri gaming",
            "Mouse gaming", "Tastaturi gaming", "Mousepad gaming",
            "Carti", "Muzica si filme",
            "Instrumente muzicale", "Birotica", "Rechizite scolare",
        ],
        "Fashion": [
            "Imbracaminte femei", "Imbracaminte barbati",
            "Imbracaminte copii",
            "Incaltaminte femei", "Incaltaminte barbati",
            "Incaltaminte copii", "Genti femei",
            "Rucsacuri", "Portofele", "Bijuterii",
            "Ceasuri", "Ochelari de soare",
            "Accesorii vestimentare",
        ],
        "Ingrijire personala & Cosmetice": [
            "Parfumuri femei", "Parfumuri barbati",
            "Creme si seruri ten", "Creme de corp",
            "Lotiuni de corp", "Geluri de dus",
            "Ingrijire par", "Sampoane", "Balsamuri",
            "Masti par", "Vopsea par", "Aparate de coafat",
            "Uscatoare de par", "Epilatoare",
            "Aparate de ras electrice", "Perii de dinti electrice",
            "Irigatoare orale", "Produse make-up",
            "Fond de ten", "Ruj si gloss",
            "Vitamine si suplimente", "Produse dieta",
            "Tensiometre", "Termometre", "Glucometre",
        ],
        "Casa, Gradina & Bricolaj": [
            "Mobila living", "Mobila dormitor",
            "Mobila birou", "Mobila bucatarie",
            "Corpuri de iluminat", "Becuri", "Benzi LED",
            "Smart home", "Prize si intrerupatoare inteligente",
            "Camere supraveghere", "Sisteme alarma",
            "Scule electrice", "Scule manuale",
            "Masini de tuns iarba", "Suflante frunze",
            "Pompe apa", "Unelte gradinarit",
            "Textile casa", "Lenjerii pat",
            "Prosoape", "Perdele si draperii",
            "Covoare si mochete",
        ],
        "Sport & Travel": [
            "Biciclete", "Biciclete electrice",
            "Trotinete electrice", "Accesorii ciclism",
            "Echipament fitness", "Aparate fitness",
            "Greutati si haltere", "Saltele yoga",
            "Articole inot", "Articole schi",
            "Camping si drumetie", "Corturi",
            "Saci de dormit", "Bagaje si troler",
            "Rucsacuri voiaj",
        ],
        "Auto, Moto & RCA": [
            "GPS auto", "Camera video auto (dashcam)",
            "Anvelope vara", "Anvelope iarna",
            "Anvelope all season", "Jante",
            "Alarme si imobilizatoare", "Accesorii interior",
            "Accesorii exterior", "Ungerea si intretinerea masinii",
            "Scaune auto copii", "Motociclete si scutere",
            "Accesorii moto", "RCA",
        ],
        "Jucarii, Copii & Bebe": [
            "Jucarii 0-2 ani", "Jucarii 3-5 ani",
            "Jucarii 6-12 ani", "LEGO",
            "Jocuri de societate", "Puzzle",
            "Figurine si colectii", "Jucarii RC",
            "Carucioare", "Scaune auto copii",
            "Patuturi si accesorii", "Hrana bebe",
            "Ingrijire bebe", "Baby monitor",
            "Haine copii",
        ],
        "Bacanie": [
            "Cafea si ceai", "Bauturi racoritoare",
            "Apa plata si minerala", "Sucuri",
            "Bauturi energizante", "Capsule cafea",
            "Produse bio", "Suplimente alimentare sport",
            "Hrana animale companie",
        ],
    },

    "pcgarage": {
        "Laptop & Notebook": [
            "Laptop gaming", "Laptop office / business",
            "Laptop 2 in 1", "Genti si rucsacuri laptop",
            "Standuri si coolere laptop", "Accesorii laptop",
        ],
        "Sisteme PC": [
            "PC Gaming", "PC Office", "Workstation",
            "Servere AI", "All-in-One PC", "Mini PC", "Desktop PC",
        ],
        "Componente PC": [
            "Placi video", "Procesoare", "Placi de baza",
            "Memorii RAM", "SSD", "HDD", "Surse PC",
            "Carcase", "Coolere procesor",
            "Ventilatoare carcasa", "Pasta termoconductoare",
        ],
        "Periferice": [
            "Monitoare", "Tastaturi", "Mouse-uri", "Mousepad-uri",
            "Casti audio", "Casti gaming", "Boxe", "Microfoane",
            "Webcam-uri", "Gamepad-uri si controllere",
        ],
        "Gaming": [
            "Scaune gaming", "Birouri gaming", "Accesorii gaming",
        ],
        "Retea & Conectivitate": [
            "Routere wireless", "Switch-uri", "Access point-uri",
            "NAS", "Modemuri", "Cabluri retea", "UPS", "Antene",
        ],
        "Stocare externa": [
            "SSD extern", "HDD extern", "USB flash drive",
            "Carduri de memorie", "Cititoare carduri",
        ],
        "Telefoane & Tablete": [
            "Smartphones", "Tablete", "Smartwatch-uri",
            "Accesorii telefoane", "Accesorii tablete",
        ],
        "Smart Home & Supraveghere": [
            "Camere supraveghere", "Sisteme alarma",
            "Dispozitive smart home", "Becuri smart", "Prize smart",
        ],
        "Electrocasnice": [
            "Aer conditionat", "Aspiratoare", "Aspiratoare robot",
            "Aparate de gatit", "Cafetiere", "Blendere",
            "Combine frigorifice", "Congelatoare",
            "Masini de spalat rufe",
        ],
        "Foto & Video": [
            "Aparate foto", "Camere video", "Drone",
            "Accesorii foto-video", "Trepieduri",
        ],
        "Cabluri & Adaptoare": [
            "Cabluri USB", "Cabluri HDMI", "Cabluri DisplayPort",
            "Adaptoare si huburi", "Cabluri audio",
        ],
        "TV & Audio": [
            "Televizoare", "Boxe portabile",
            "Soundbar-uri", "Proiectoare",
        ],
        "Printing": [
            "Imprimante", "Multifunctionale", "Cartuse si tonere",
            "Imprimante 3D", "Accesorii imprimante 3D",
        ],
        "Software": [
            "Sisteme de operare", "Office", "Antivirus", "Jocuri PC",
        ],
    },

    "farmaciatei": {
        "Medicamente OTC": [
            "Raceala, gripa si tuse", "Durere si febra",
            "Digestive si antiacide", "Alergii",
            "Dermatologie", "Afectiuni urinare",
            "Afectiuni cardiovasculare", "Afectiuni respiratorii",
            "Oftalmologie", "Stomatologie si ingrijire orala",
            "Somn si stres", "Sistem nervos",
            "Afectiuni articulare",
        ],
        "Vitamine & Suplimente": [
            "Vitamine si minerale", "Multivitamine",
            "Vitamina C", "Vitamina D", "Magneziu", "Zinc",
            "Omega 3", "Probiotice si prebiotice", "Imunitate",
            "Sport si fitness", "Colagen", "Adaptogene",
            "Antioxidanti",
        ],
        "Dermato-cosmetice": [
            "Ingrijire ten normal/mixt", "Ingrijire ten uscat",
            "Ingrijire ten gras/acneic", "Ingrijire ten sensibil",
            "Seruri pentru ten", "Creme antirid",
            "Protectie solara", "Ingrijire zona ochi",
            "Curatare ten", "Ingrijire corp",
            "Ingrijire maini si unghii",
        ],
        "Cosmetice premium": [
            "Parfumuri", "Make-up", "Fond de ten",
            "Ruj si gloss", "Rimel si creion ochi",
            "Ingrijire par premium", "Tratamente par",
        ],
        "Ingrijire personala": [
            "Igiena dentara", "Periute electrice",
            "Ata dentara si irigatoare", "Deodorante",
            "Depilare", "Igiena intima",
            "Ingrijire barbierit", "Produse feminine",
        ],
        "Dieta & Wellness": [
            "Produse pentru slabit", "Substitute de masa",
            "Ceaiuri medicinale", "Produse dietetice",
            "Batoane si gustari sanatoase",
        ],
        "Viata sexuala": [
            "Prezervative", "Lubrifianti",
            "Fertilitate si contraceptie",
        ],
        "Dispozitive medicale": [
            "Tensiometre", "Glucometre si consumabile",
            "Termometre", "Pulsioximetru", "Pansamente",
            "Ortopedice si suporturi", "Lentile de contact",
        ],
        "Animale de companie": [
            "Hrana caini", "Hrana pisici",
            "Tratamente antiparazitare", "Accesorii animale",
        ],
    },

    "sole": {
        "Protectie solara": [
            "Creme protectie solara fata",
            "Creme protectie solara corp",
            "Creme protectie solara copii",
            "Spray protectie solara",
            "Creme autobronzante", "Spray autobronzant",
            "Gel autobronzant", "Mist autobronzant",
        ],
        "Ingrijire ten": [
            "Creme de zi", "Creme de noapte",
            "Seruri pentru ten", "Seruri de noapte",
            "Ampoule (fiole concentrate)", "Esente (essence)",
            "Toner / Lotiuni tonice", "Masti pentru ten",
            "Sheet mask", "Tratamente locale (spot treatment)",
            "BB Cream / CC Cream", "Primer",
            "Crema ochi", "Gel ochi", "Patch-uri ochi",
            "Exfoliant / Peeling",
        ],
        "Demachierea si curatarea tenului": [
            "Ulei demachiant", "Balsam demachiant",
            "Spuma de curatare", "Gel de curatare",
            "Apa micelara", "Discuri demachiante",
            "Exfoliant mecanic", "Apa termica",
        ],
        "Tonifiere si calmare": [
            "Lotiuni tonice", "Mist facial",
            "Seruri calmante", "Tratamente pentru roseata",
        ],
        "Ingrijire par": [
            "Sampoane", "Balsam de par", "Masti de par",
            "Seruri de par", "Tratamente par vopsit",
            "Tratamente anti-cadere", "Uleiuri de par",
            "Leave-in conditioner",
        ],
        "Ingrijire corp": [
            "Creme de corp", "Lotiuni de corp", "Uleiuri de corp",
            "Geluri de dus", "Scrub de corp",
            "Sapunuri lichide", "Creme de maini",
            "Mist pentru corp", "Crema pentru picioare",
        ],
        "Machiaj": [
            "Fond de ten", "Concealer", "Pudra", "Blush",
            "Bronzer", "Iluminator (highlighter)", "Contur",
            "Fard de pleoape", "Rimel", "Eyeliner",
            "Creion de ochi", "Ruj", "Gloss de buze",
            "Lip liner", "Sprancene", "Seturi makeup",
        ],
        "Igiena orala": [
            "Periute de dinti electrice", "Paste de dinti",
            "Ape de gura", "Produse de albire dinti",
            "Ata dentara",
        ],
        "Parfumuri": [
            "Parfumuri femei", "Parfumuri barbati",
            "Parfumuri unisex",
        ],
        "Accesorii beauty": [
            "Perii makeup", "Bureti makeup",
            "Role de jad si cuart", "Gua sha",
            "Benzi curatare nasi", "Dispozitive ingrijire ten",
        ],
        "Sanatate": [
            "Suplimente", "Vitamine", "Ceaiuri",
        ],
    },
}

KNOWN_SOURCES = list(SOURCE_CATEGORIES.keys())


def get_subcategories(source: str, main_category: str) -> list[str]:
    return SOURCE_CATEGORIES.get(source, {}).get(main_category, [])


def get_main_categories(source: str) -> list[str]:
    return list(SOURCE_CATEGORIES.get(source, {}).keys())
